export enum TreeRelationType {
    "MARRIED" = "MARRIED",
    "DESCENDANT" = "DESCENDANT",
    "MARRIED-SUBTREE" = "MARRIED-SUBTREE",
    "MARRIEDSUBTREEDESCENDANT" = "MARRIEDSUBTREEDESCENDANT",
    "MARRIEDDESCENDANT" = "MARRIEDDESCENDANT",
    "MARRIEDDESCENDANTSUBTREE" = "MARRIEDDESCENDANTSUBTREE",
    "ASCENDANT" = "ASCENDANT",
    "ASCENDANTMARRIED" = "ASCENDANTMARRIED",
    "ANCESTOR" = "ANCESTOR",
    "ANCESTORMARRIED" = "ANCESTORMARRIED",
}
